### ISSUE TITLE
RSCPKeyError

### ISSUE THREAD

**Issue by drizzd** [torbennehmer/hacs-e3dc#140]
## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v7+
arch | armv7l
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11. April 2024 um 16:33
-- | --
current_recorder_run | 22. April 2024 um 22:38
estimated_db_size | 238.18 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I started using hacs-e3dc in November 2023. I updated E3DC to latest firmware 2 weeks ago. Shortly after I updated hacs-e3dc from 3.4.2 to 3.6.2 for #118. Since then RSCPKeyError was raised twice: In e3dc.poll on April 18 and in get_manual_charge->sendRequest on April 22. In e3dc_proxy.py we raise ConfigEntryAuthFailed on RSCPKeyError. This causes Home Assistant to stop the integration until the user manually re-authenticates.

The issue does not appear to be related to authentication. I have not changed my passwords and I re-authenticate successfully with the same credentials. Removing the RSCPKeyError clause fixes the issue for me.

```diff
@@ -40,11 +41,6 @@ def e3dc_call(func):
         except AuthenticationError as ex:
             _LOGGER.exception("Failed to authenticate with E3DC: %s", ex)
             raise ConfigEntryAuthFailed("Failed to authenticate with E3DC") from ex
-        except RSCPKeyError as ex:
-            _LOGGER.exception("Encryption error with E3DC, key invalid: %s", ex)
-            raise ConfigEntryAuthFailed(
-                "Encryption Error with E3DC, key invalid"
-            ) from ex
         except (HomeAssistantError, ConfigEntryAuthFailed):
             raise
         except Exception as ex:
```

### Reproduction steps

To reproduce I made the following change.

```diff
@@ -119,6 +120,9 @@ class E3DCProxy:
     def get_manual_charge(self) -> dict[str, Any]:
         """Poll manual charging state."""
         try:
+            if random.random() > 0.99:
+                self.e3dc.disconnect()
+                raise RSCPKeyError
             data = self.e3dc.sendRequest(
                 (RscpTag.EMS_REQ_GET_MANUAL_CHARGE, RscpType.NoneType, None), keepAlive=True
             )
```

### Debug logs

```text
It takes several days until the issue triggers. Please let me know if more information is required.
```

**Comment by torbennehmer** [comment]
Hi @drizzd,
I haven't seen or heared of random authentication losses from anywhere else. Could you please check against at least 3.7.0, I've added some protection against update loop exceptions here.
If it still happens, I have to have a debug log and - if possible - a diag dump before and after reauthentication to have a clue here what happens. 
Please ensure, that you don't have any connectivity issues here, this could be related to intermittent network outages as well.
Right now, I'll close the task as I can't do anything here, but please feel free to reopen it with the required information if the problem occurs again as outlined above.
Cheers, Torben
