### ISSUE TITLE
Sensors for the E3DC Wallbox

### ISSUE THREAD

**Issue by Crash09N** [torbennehmer/hacs-e3dc#146]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No, I don't think so.

### Describe the solution you'd like

Just a way to see the usage of the E3DC Wallbox

### Describe alternatives you've considered

None.

**Comment by torbennehmer** [comment]
Duplicate for #47 and #90 
**Please check existing issues before creating new ones.**
