### ISSUE TITLE
Availibility of PV Forecast

### ISSUE THREAD

**Issue by bs0001** [torbennehmer/hacs-e3dc#191]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Extension of current data values

### Describe the solution you'd like

Providing of PV Forecast would be quite helpful.

### Describe alternatives you've considered

n/a

**Comment by torbennehmer** [comment]
Please use the [HA built-in PV forecast. ](https://www.home-assistant.io/integrations/forecast_solar)
I've not checked if the E3DC forecast is even available, but even if, I wouldn't use it. At least in my case, HAs forecast is way more accurate than what my E3DC units shows me.
