### ISSUE TITLE
Availibility of S10E Firmware Version

### ISSUE THREAD

**Issue by bs0001** [torbennehmer/hacs-e3dc#192]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Extension of current data values

### Describe the solution you'd like

Providing of S10 E Firmware Version would be quite helpful.
Complete Firmware version (e.g. P10_2024_028) will be good. In S10E you won't see the last figure.

### Describe alternatives you've considered

n/a

**Comment by torbennehmer** [comment]
Go check your Device page :)
![image](https://github.com/user-attachments/assets/0a548e9f-f596-4b72-baed-99dc219359bf)
