### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by liefersfl** [torbennehmer/hacs-e3dc#28]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I was not sure which user / password i should enter. Also the rscp password i set did not work

### Describe the solution you'd like

Please add following information to the README.md:

- Which username / password one should enter
- Which rscp password characters are allowed to use

### Describe alternatives you've considered

Improve the error message in the ha dialog and suggest solutions like changing the rscp password

### Additional context

-

**Comment by torbennehmer** [comment]
see also #27
