### ISSUE TITLE
E3DC blackout times

### ISSUE THREAD

**Issue by Thomansky** [torbennehmer/hacs-e3dc#53]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

...

### Describe the solution you'd like

Hello,

I've tried out the project and I really like it! It would be great, however, if the option to set blackout times could be added. Additionally, I would appreciate it if the power meter could be integrated not only for consumption but also for additional production. I use an E3/DC S10 Pro with an additional battery pack, an E3/DC SWR123 (an external inverter from E3/DC), and one from SolarEdge. One has an internal power meter that is not currently displayed, and the other has an external power meter, also not displayed. I also have two wall chargers (not the new ones, but the ones with e3dc branding from Walbe). If you need any data or information, I am happy to provide it. Please note, though, that my programming skills are limited.

Thank you very much for your hard work on this project!
<img width="945" alt="Bildschirmfoto 2023-09-10 um 22 35 40" src="https://github.com/torbennehmer/hacs-e3dc/assets/73141171/c4967a91-3b99-499a-b8a2-6bb0e2cd6223">

### Describe alternatives you've considered

.....

**Comment by neuromancer3142** [comment]
Hi Thomansky, 
I use an S10E Pro and found the following sensor when looking through all S10 entities: "sensor.s10e_pro_additional_source_production". I simply had to unmask / enable it and then I was able to see the wattage produced by my external source, i.e. my second inverter. Perhaps this might at least partially solve your point mentioned above.
All the best ...

**Comment by torbennehmer** [comment]
@Thomansky please don't file multiple feature requrests in one issue (you checked it off, did you). Also, please provide the diagnostic dump if it works on your installation (there is an issue open I don't yet understand that can break it).
As for the additional powermeters, there is an issue open already (#23, possibly along with #43 or #44 possibly).
AS for the wallbox, there too is an issue open already (#47).
Please check them first, then reopen a new issue per item missing yet.
Thanks!
