### ISSUE TITLE
Make E3DC Portal "Actual Data" also available as sensors.

### ISSUE THREAD

**Issue by ubarni** [torbennehmer/hacs-e3dc#60]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to show the actual data (as shown in the E3DC Portal "Aktuelle Werte") also in my Home Assistant dashboard.

### Describe the solution you'd like

It would be helpful to have the https://python-e3dc.readthedocs.io/en/latest/e3dc.html#e3dc.E3DC.poll_rscp function from [python-e3dc](https://github.com/fsantini/python-e3dc) implemented to get values for the following sensors:

- consumption.battery -> sensor.E3DC_battery_power
- consumption.house -> sensor.E3DC_house_power
- consumption.wallbox -> sensor.E3DC_wallbox_power

- production.solar -> sensor.E3DC_solar_power
- production.add -> sensor.E3DC_add_power
- production.grid -> sensor.E3DC_grid_power

### Describe alternatives you've considered

I already use a MODBUS implementation of E3DC which delivers these values.
But i would like to migrate this to your E3DC RSCP implementation.

**Comment by torbennehmer** [comment]
This information is available, it's the core feature of the integration.
