### ISSUE TITLE
How to discharge battery?

### ISSUE THREAD

**Issue by tschrenk** [torbennehmer/hacs-e3dc#63]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Is there a way to discharge the battery? I tried to use the manual_charge with a negative value but that does not seem to work.

Use case is that in spring I get >12 kW from the roof but the inverter can only process 12 kW. If the battery has space it can store the additional power >12kW otherwise it is lost.

Idea was to discharge the battery by e.g. for 2 kW to make room for the delta from the roof. In that case if I get 13KW from the roof 1kW is directly stored in the battery.

### Describe the solution you'd like

A solution would be to allow negative values for the manual_charge service. Then the battery is discharged for that value.

### Describe alternatives you've considered

A separate discharge-battery service.

**Comment by torbennehmer** [comment]
Forced discharging of the battery (possibly into the grid) is not on my list of things, I'm not even sure if RSCP would allow that in the first place. Also, I'm not even sure, if you may actually transfer power from the battery to the grid.
Apart from that I'm not even sure if what you think would work, you can't discharge and charge simultaneously, also, unneccessary should be avoided as you'll have a conversion loss each time as well. 
Thus, I won't provide a feature like this.
